name: Heroku Deploy

on:
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    name: Heroku deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: eitango-test-api
          heroku_email: ${{secrets.HEROKU_EMAIL}}